name: ${project.name}
description: ${project.description}
author: quantiom
version: ${project.version}
main: me.quantiom.advancedvanish.AdvancedVanishPlugin
softdepend: [LuckPerms, PlaceholderAPI, GroupManager, PermissionsEx, bPermissions, DiscordSRV, Dynmap, squaremap, LibsDisguises, PlayerParticles, Essentials, PlaceholderAPI, ProtocolLib]
api-version: 1.20
commands:
  vanish:
    description: The main vanish command.
    aliases: [v, advancedvanish]
    usage: /vanish

libraries:
- 'redis.clients:jedis:5.1.0'
